// const products =[
//     {
//         id:1,
//         image:'images/prod1W.jpg',
//         name:'Bicycle 29 ',
//         price: 3200,
//     },
// {id:2,
//         image:'images/prod2M.jpg',
//         name:'Bicycle 17',
//         price: 3100,},
// {id:3,
//         image:'images/prod3M.jpg',
//         name:'Bicycle 28',
//         price: 3000,},
// {id:4,
//             image:'images/prod4M.jpg',
//             name:'Bicycle 27',
//             price: 1700,},
// {
//     id:5,
//         image:'images/prod5K.jpg.png',
//         name:'Bicycle 26',
//         price: 2050,
// },
// {
//     id:6,
//         image:'images/prod6K.jpg',
//         name:'Bicycle 26',
//         price: 2100,
// },
// {id:7,
//         image:'images/Prod8T.jpg',
//         name:'Bicycle 24',
//         price:2400 ,
// },
// {id:8,
//         image:'images/prod9K.jpg',
//         name:'Bicycle 23',
//         price:2750 ,
// },
// {id:9,
//         image:'images/prod10E.jpg',
//         name:'Bicycle 27',
//         price: 3000,
// },
// {id:10,
//         image:'images/Prod11U.jpg',
//         name:'Bicycle 22',
//         price:900 ,
// },
// {id:11,
// image:'images/prod12M.jpg',
// name:'Bicycle 21',
// price:2500 ,
// },
// {id:12,
// image:'images/prod13T.jpg',
// name:'Bicycle 20',
// price:1500 ,
// },
// {id:13,
// image:'images/prod14U.jpg',
// name:'Bicycle 19',
// price:1000 ,
// },
// {id:14,
// image:'images/prod15W.png',
// name:'Bicycle 18',
// price:2450 ,
// },
// {id:15,
// image:'images/prod17W.jpg',
// name:'Bicycle 2',
// price:2000 ,
// },
// {id:16,
// image:'images/prod18M.jpg',
// name:'Bicycle 3',
// price: 2700,
// },
// {id:17,
// image:'images/prod19K.jpg',
// name:'Bicycle 4',
// price: 5000,
// },
// {id:18,
// image:'images/prod20AS.jpg',
// name:'Accessories 1',
// price: 4650,
// },
// {id:19,
// image:'images/prod21AS.jpg',
// name:'Accessories 2',
// price:4750 ,
// },
// {id:20,
// image:'images/prod21K.jpg',
// name:'Bicycle 5',
// price: 4900,
// },
// {id:21,
// image:'images/prod22AS.jpg',
// name:'Accessories 5',
// price:4800 ,
// },
// {id:22,
// image:'images/prod23AS.jpeg',
// name:'Assessories 6',
// price: 4700,
// },
// {id:23,
// image:'images/prod24AS.jpg',
// name:'Assessories 7',
// price:4600 ,
// },
// {id:22,
// image:'images/prod23AS.jpeg',
// name:'Assessories 6',
// price: 4700,
// },
// {id:23,
// image:'images/prod25K.jpg',
// name:'Bicycle 7',
// price:4300,
// },
// {id:24,
// image:'images/prod26U.jpg',
// name:'Bicycle 8',
// price:4200,
// },
// {id:25,
// image:'images/prod27UT.jpg',
// name:'Bicycle 9',
// price:4100,
// },
// {id:26,
// image:'images/prod28U.jpg',
// name:'Bicycle 10',
// price:4000,
// },
// {id:27,
// image:'images/prod29U.jpg',
// name:'Bicycle 11',
// price:2070,
// },
// {id:28,
// image:'images/Prod30W.jpg',
// name:'Bicycle 12',
// price:5500,
// },
// {id:29,
// image:'images/prod31W.jpg',
// name:'Bicycle 13',
// price:3600,
// },
// {id:30,
// image:'images/prod33ClothM.jpg',
// name:'Clothes 1',
// price:3500,
// },
// {id:31,
// image:'images/prod34UT.jpg',
// name:'Bicucle 14',
// price:3400,
// },
// {id:32,
// image:'images/prod35UT.jpeg',
// name:'Bicycle 15',
// price:2850,
// },
// {id:33,
// image:'images/prod36UT.jpg.png',
// name:'Bicycle 17',
// price:2600,
// },
// {id:34,
// image:'images/prodCloth32M.jpg',
// name:'Clothes 2',
// price:2900,
// },
// {id:35,
// image:'images/top7.jpg',
// name:'Bicycle 1',
// price:3300,
// }

// ];

// const product =[
//         {
//             id:1,
//             image:'images/prod1W.jpg',
//             name:'Bicycle 29 ',
//             price: 3200,
//         },
//     {id:2,
//             image:'images/prod2M.jpg',
//             name:'Bicycle 17',
//             price: 3100,},
//     {id:3,
//             image:'images/prod3M.jpg',
//             name:'Bicycle 28',
//             price: 3000,},
//     {id:4,
//                 image:'images/prod4M.jpg',
//                 name:'Bicycle 27',
//                 price: 1700,},
//     {
//         id:5,
//             image:'images/prod5K.jpg.png',
//             name:'Bicycle 26',
//             price: 2050,
//     },
//     {
//         id:6,
//             image:'images/prod6K.jpg',
//             name:'Bicycle 26',
//             price: 2100,
//     },
